import { MigrationInterface, QueryRunner } from "typeorm";

export class CleanMigrationOfAllTables1775399927932 implements MigrationInterface {
    name = 'CleanMigrationOfAllTables1775399927932'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`degree_types\` (\`id\` tinyint NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL COMMENT 'Undergraduate, Masters, PhD, Diploma', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fields_of_study\` (\`id\` smallint NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL COMMENT 'Engineering, Medicine, Law, etc.', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL, \`description\` text NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_roles_name\` (\`name\`), UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_applications\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`status\` enum ('pending', 'submitted', 'accepted', 'rejected') NOT NULL DEFAULT 'pending', \`applied_at\` timestamp NULL, \`user_id\` bigint NOT NULL, \`scholarship_id\` bigint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scrape_jobs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`source_url\` varchar(500) NOT NULL, \`status\` enum ('pending', 'running', 'completed', 'failed') NOT NULL DEFAULT 'pending', \`scholarships_found\` int NOT NULL DEFAULT '0', \`error_message\` text NULL, \`started_at\` timestamp NULL, \`completed_at\` timestamp NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_profiles\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`user_id\` bigint NOT NULL, \`date_of_birth\` date NULL, \`gender\` varchar(20) NULL COMMENT 'MALE, FEMALE, OTHER, PREFER_NOT_TO_SAY', \`nationality\` varchar(100) NULL COMMENT 'Country of citizenship', \`address\` text NULL COMMENT 'Full street address', \`city\` varchar(100) NULL COMMENT 'City of residence', \`state\` varchar(100) NULL COMMENT 'State or province', \`postal_code\` varchar(20) NULL COMMENT 'ZIP or postal code', \`profile_picture_url\` varchar(500) NULL COMMENT 'Profile photo URL', \`profile_picture_public_id\` varchar(255) NULL COMMENT 'Cloudinary public ID', \`highest_education\` varchar(200) NULL COMMENT 'Highest degree obtained', \`field_of_study\` varchar(200) NULL COMMENT 'Major or field of study', \`institution_name\` varchar(255) NULL COMMENT 'Name of institution', \`graduation_year\` int NULL COMMENT 'Year of graduation', \`gpa\` decimal(3,2) NULL COMMENT 'Grade point average', \`english_proficiency\` varchar(50) NULL COMMENT 'IELTS, TOEFL score', \`work_experience\` text NULL COMMENT 'Professional work history', \`linkedin_url\` varchar(500) NULL COMMENT 'LinkedIn profile URL', \`portfolio_url\` varchar(500) NULL COMMENT 'Personal portfolio URL', \`bio\` text NULL COMMENT 'Personal statement or bio', \`is_complete\` tinyint(1) NOT NULL COMMENT 'Profile completion status' DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`idx_user_profiles_is_complete\` (\`is_complete\`), INDEX \`idx_user_profiles_user_id\` (\`user_id\`), UNIQUE INDEX \`IDX_6ca9503d77ae39b4b5a6cc3ba8\` (\`user_id\`), UNIQUE INDEX \`REL_6ca9503d77ae39b4b5a6cc3ba8\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`role_id\` bigint NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`first_name\` varchar(100) NOT NULL, \`last_name\` varchar(100) NOT NULL, \`is_active\` tinyint(1) NOT NULL DEFAULT 1, \`phone_number\` varchar(20) NULL, \`country\` varchar(100) NULL, \`reset_password_token\` varchar(500) NULL, \`reset_password_expires_at\` datetime NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, INDEX \`idx_users_role_id\` (\`role_id\`), INDEX \`idx_users_email\` (\`email\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`saved_scholarships\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` bigint NOT NULL, \`scholarship_id\` bigint NOT NULL, UNIQUE INDEX \`unique_save\` (\`user_id\`, \`scholarship_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`schools\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NULL, \`city\` varchar(100) NULL, \`website_url\` varchar(500) NULL, \`description\` text NULL, \`logo_url\` varchar(500) NULL, \`logo_public_id\` varchar(255) NULL, \`ranking\` int NULL, \`partner_status\` enum ('partner', 'non_partner') NOT NULL DEFAULT 'non_partner', \`is_active\` tinyint NOT NULL DEFAULT 1, \`country_id\` smallint NOT NULL, INDEX \`idx_schools_slug\` (\`slug\`), INDEX \`idx_schools_country\` (\`country_id\`), INDEX \`idx_schools_name\` (\`name\`), UNIQUE INDEX \`IDX_150b12170135ff067a24ea270d\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`programs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`course_name\` varchar(255) NOT NULL, \`duration\` varchar(100) NULL, \`intake_periods\` json NULL COMMENT 'Array of intake periods e.g ["September", "January"]', \`application_deadline\` timestamp NULL, \`language_requirements\` varchar(255) NULL, \`tuition_fee\` decimal(10,2) NULL, \`currency\` char(3) NULL COMMENT 'ISO 4217 currency code e.g USD, GBP', \`payment_plan_options\` json NULL COMMENT 'Array of payment plan options', \`is_active\` tinyint NOT NULL DEFAULT 1, \`school_id\` bigint NOT NULL, \`degree_type_id\` tinyint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarships\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`title\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL COMMENT 'SEO-friendly URL identifier', \`description\` text NULL, \`eligibility\` text NULL COMMENT 'Eligibility criteria and requirements', \`funding_type\` enum ('full', 'partial', 'unknown') NOT NULL DEFAULT 'unknown', \`coverage\` json NULL COMMENT 'Array of coverage types: tuition, living, travel, etc.', \`application_url\` varchar(500) NULL COMMENT 'External application link', \`status\` enum ('open', 'closed', 'upcoming') NOT NULL DEFAULT 'upcoming', \`amount\` decimal(10,2) NULL COMMENT 'Full scholarship value', \`discounted_amount\` decimal(10,2) NULL COMMENT 'Discounted amount if applicable', \`currency\` char(3) NULL COMMENT 'ISO 4217 currency code e.g USD, GBP', \`source\` enum ('admin', 'scraped', 'imported') NOT NULL DEFAULT 'admin', \`source_url\` varchar(500) NULL COMMENT 'Origin URL if scraped/imported', \`deadline\` date NULL, \`is_published\` tinyint NOT NULL COMMENT 'Published and visible to students' DEFAULT 0, \`is_featured\` tinyint NOT NULL COMMENT 'Featured/highlighted scholarship' DEFAULT 0, \`created_by\` bigint NULL COMMENT 'FK to users table - admin who created it', INDEX \`idx_funding_type\` (\`funding_type\`), INDEX \`idx_status\` (\`status\`), INDEX \`idx_source\` (\`source\`), INDEX \`idx_deadline\` (\`deadline\`), INDEX \`idx_is_published\` (\`is_published\`), FULLTEXT INDEX \`ft_scholarship_search\` (\`title\`, \`description\`), UNIQUE INDEX \`IDX_7eb0b5c1fc27d6a1f1b98f18ca\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`countries\` (\`id\` smallint NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`code\` char(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2 (e.g., NG, GB, US)', UNIQUE INDEX \`IDX_b47cbb5311bad9c9ae17b8c1ed\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tags\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d90243459a697eadb8ad56e909\` (\`name\`), UNIQUE INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_tags\` (\`post_id\` varchar(255) NOT NULL, \`tag_id\` varchar(255) NOT NULL, INDEX \`IDX_192ab488d1c284ac9abe2e3035\` (\`tag_id\`), PRIMARY KEY (\`post_id\`, \`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comments\` (\`id\` varchar(36) NOT NULL, \`parent_id\` varchar(255) NULL, \`content\` text NOT NULL, \`status\` enum ('PENDING', 'APPROVED', 'PUBLISHED', 'HIDDEN', 'DELETED') NOT NULL, \`likes_count\` int NOT NULL DEFAULT '0', \`dislikes_count\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`post_id\` varchar(36) NULL, \`user_id\` bigint NULL, INDEX \`IDX_d6f93329801a93536da4241e38\` (\`parent_id\`), INDEX \`IDX_2d41293984790c4b92ea0a1b73\` (\`post_id\`, \`status\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`posts\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`featured_image_url\` varchar(255) NULL, \`content\` text NOT NULL, \`author_id\` bigint NOT NULL, \`read_time_minutes\` int UNSIGNED NULL, \`status\` enum ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED') NOT NULL, \`scheduled_at\` timestamp NULL, \`published_at\` timestamp NULL, \`seo_meta_title\` varchar(255) NULL, \`seo_meta_description\` varchar(500) NULL, \`views_count\` int UNSIGNED NOT NULL DEFAULT '0', \`likes_count\` int NOT NULL DEFAULT '0', \`comments_count\` int NOT NULL DEFAULT '0', \`is_featured\` tinyint NOT NULL DEFAULT 0, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`IDX_32e926dc2d4b4ec5beaa2e1bfc\` (\`is_featured\`), INDEX \`IDX_312c63be865c81b922e39c2475\` (\`author_id\`), INDEX \`IDX_3cb61174373fe05492433f5811\` (\`status\`, \`published_at\`), UNIQUE INDEX \`IDX_54ddf9075260407dcfdd724857\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_categories\` (\`post_id\` varchar(255) NOT NULL, \`category_id\` varchar(255) NOT NULL, INDEX \`IDX_f6e2655c798334198182db6399\` (\`category_id\`), PRIMARY KEY (\`post_id\`, \`category_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`description\` text NULL, \`seo_meta_title\` varchar(255) NULL, \`seo_meta_description\` varchar(255) NULL, \`is_enabled\` tinyint NOT NULL DEFAULT 1, \`created_by\` bigint NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_8b0be371d28245da6e4f4b6187\` (\`name\`), UNIQUE INDEX \`IDX_420d9f679d41281f282f5bc7d0\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_likes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`post_id\` varchar(255) NOT NULL, \`user_id\` bigint NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_8f64693922a9e8c4e2605850d0\` (\`post_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`saved_posts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`post_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` bigint NULL, UNIQUE INDEX \`IDX_f20a36cb4746cdc9d4012e636d\` (\`userId\`, \`post_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comment_reactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`comment_id\` varchar(255) NOT NULL, \`reaction\` enum ('LIKE', 'DISLIKE') NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` bigint NULL, UNIQUE INDEX \`IDX_1b883ab118d832640b031ab685\` (\`comment_id\`, \`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comment_reports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`comment_id\` varchar(255) NOT NULL, \`reason\` text NOT NULL, \`status\` enum ('PENDING', 'REVIEWED', 'RESOLVED') NOT NULL DEFAULT 'PENDING', \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`reportedById\` bigint NULL, \`reviewedById\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_views_events\` (\`id\` int NOT NULL AUTO_INCREMENT, \`post_id\` varchar(255) NOT NULL, \`viewed_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` bigint NULL, INDEX \`IDX_0c47f4aa3008e5d1c0d30048de\` (\`post_id\`, \`viewed_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_popularity_stats\` (\`id\` varchar(36) NOT NULL, \`period\` enum ('WEEKLY', 'MONTHLY') NOT NULL, \`period_start\` date NOT NULL, \`views_count\` int NOT NULL DEFAULT '0', \`likes_count\` int NOT NULL DEFAULT '0', \`comments_count\` int NOT NULL DEFAULT '0', \`calculated_at\` timestamp NOT NULL, \`postId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_eligible_countries\` (\`scholarship_id\` bigint NOT NULL, \`country_id\` smallint NOT NULL, INDEX \`IDX_eff92e5dc34bb9ffeb9b1e3b4c\` (\`scholarship_id\`), INDEX \`IDX_980003b4cdcb862dc740e58ee9\` (\`country_id\`), PRIMARY KEY (\`scholarship_id\`, \`country_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_host_countries\` (\`scholarship_id\` bigint NOT NULL, \`country_id\` smallint NOT NULL, INDEX \`IDX_7eac5b06ff5f374ed6ff798b39\` (\`scholarship_id\`), INDEX \`IDX_8a77965357545fbb4b27809088\` (\`country_id\`), PRIMARY KEY (\`scholarship_id\`, \`country_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_degree_types\` (\`scholarship_id\` bigint NOT NULL, \`degree_type_id\` tinyint NOT NULL, INDEX \`IDX_1f424f8e81b88a5b8ab53932e3\` (\`scholarship_id\`), INDEX \`IDX_6a139df90c2b125c3f47ca1431\` (\`degree_type_id\`), PRIMARY KEY (\`scholarship_id\`, \`degree_type_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_fields_of_study\` (\`scholarship_id\` bigint NOT NULL, \`field_id\` smallint NOT NULL, INDEX \`IDX_2a8f694223eaff9cba77ee59a7\` (\`scholarship_id\`), INDEX \`IDX_6fd5f51e72b59a7b1f732b2a37\` (\`field_id\`), PRIMARY KEY (\`scholarship_id\`, \`field_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_programs\` (\`scholarship_id\` bigint NOT NULL, \`program_id\` bigint NOT NULL, INDEX \`IDX_ba2c20eccaff4301d1f5849164\` (\`scholarship_id\`), INDEX \`IDX_b9241075eedae37c941e50cc6b\` (\`program_id\`), PRIMARY KEY (\`scholarship_id\`, \`program_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`scholarship_schools\` (\`scholarship_id\` bigint NOT NULL, \`school_id\` bigint NOT NULL, INDEX \`IDX_4eff743284ccff252264c23cb7\` (\`scholarship_id\`), INDEX \`IDX_3fef790df49da84f639d06f215\` (\`school_id\`), PRIMARY KEY (\`scholarship_id\`, \`school_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`scholarship_applications\` ADD CONSTRAINT \`FK_c278f9f1153a759bb4c0c149562\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_applications\` ADD CONSTRAINT \`FK_2c9e0c62af26956ca61f8616a7f\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_6ca9503d77ae39b4b5a6cc3ba88\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`saved_scholarships\` ADD CONSTRAINT \`FK_321ce81c5ef86b9d2b3ed875e31\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`saved_scholarships\` ADD CONSTRAINT \`FK_51b0ad1d6f628a24d9931156759\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`schools\` ADD CONSTRAINT \`FK_251565bdb89c668899132acde38\` FOREIGN KEY (\`country_id\`) REFERENCES \`countries\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD CONSTRAINT \`FK_d7a5344bdbf4566726fdc7c0a27\` FOREIGN KEY (\`school_id\`) REFERENCES \`schools\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD CONSTRAINT \`FK_94719521638e7220a028012ca42\` FOREIGN KEY (\`degree_type_id\`) REFERENCES \`degree_types\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_tags\` ADD CONSTRAINT \`FK_5df4e8dc2cb3e668b962362265d\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_tags\` ADD CONSTRAINT \`FK_192ab488d1c284ac9abe2e30356\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_259bf9825d9d198608d1b46b0b5\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_4c675567d2a58f0b07cef09c13d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_d6f93329801a93536da4241e386\` FOREIGN KEY (\`parent_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_312c63be865c81b922e39c2475e\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_categories\` ADD CONSTRAINT \`FK_becbe37977577e3eeb089b69fe1\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_categories\` ADD CONSTRAINT \`FK_f6e2655c798334198182db6399b\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_23ad9291e0e22cdf46ae7ec5461\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_likes\` ADD CONSTRAINT \`FK_b40d37469c501092203d285af80\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_likes\` ADD CONSTRAINT \`FK_9b9a7fc5eeff133cf71b8e06a7b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`saved_posts\` ADD CONSTRAINT \`FK_2a6ac38aa1767f692d4f492639b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`saved_posts\` ADD CONSTRAINT \`FK_116e9df57f5221cc1a77c3d1cfe\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_reactions\` ADD CONSTRAINT \`FK_dc714054fc62b698018fcb0ae37\` FOREIGN KEY (\`comment_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_reactions\` ADD CONSTRAINT \`FK_b9fbc058a6dd52aec6c76f9b58a\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_reports\` ADD CONSTRAINT \`FK_45a6086948851a5e791f1b7964f\` FOREIGN KEY (\`comment_id\`) REFERENCES \`comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_reports\` ADD CONSTRAINT \`FK_a7ed84b2cc95936b2b3b20051dc\` FOREIGN KEY (\`reportedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_reports\` ADD CONSTRAINT \`FK_52293400ae9e3142b0702cde49b\` FOREIGN KEY (\`reviewedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_views_events\` ADD CONSTRAINT \`FK_85814f59790f207d9d419fe6819\` FOREIGN KEY (\`post_id\`) REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_views_events\` ADD CONSTRAINT \`FK_698dc83e3d716c50f9091c3adff\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_popularity_stats\` ADD CONSTRAINT \`FK_9b73ccdda67c9b64ed499ff5616\` FOREIGN KEY (\`postId\`) REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_eligible_countries\` ADD CONSTRAINT \`FK_eff92e5dc34bb9ffeb9b1e3b4c4\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`scholarship_eligible_countries\` ADD CONSTRAINT \`FK_980003b4cdcb862dc740e58ee9c\` FOREIGN KEY (\`country_id\`) REFERENCES \`countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_host_countries\` ADD CONSTRAINT \`FK_7eac5b06ff5f374ed6ff798b390\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`scholarship_host_countries\` ADD CONSTRAINT \`FK_8a77965357545fbb4b27809088b\` FOREIGN KEY (\`country_id\`) REFERENCES \`countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_degree_types\` ADD CONSTRAINT \`FK_1f424f8e81b88a5b8ab53932e3f\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`scholarship_degree_types\` ADD CONSTRAINT \`FK_6a139df90c2b125c3f47ca14313\` FOREIGN KEY (\`degree_type_id\`) REFERENCES \`degree_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_fields_of_study\` ADD CONSTRAINT \`FK_2a8f694223eaff9cba77ee59a70\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`scholarship_fields_of_study\` ADD CONSTRAINT \`FK_6fd5f51e72b59a7b1f732b2a370\` FOREIGN KEY (\`field_id\`) REFERENCES \`fields_of_study\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_programs\` ADD CONSTRAINT \`FK_ba2c20eccaff4301d1f58491640\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`scholarship_programs\` ADD CONSTRAINT \`FK_b9241075eedae37c941e50cc6bb\` FOREIGN KEY (\`program_id\`) REFERENCES \`programs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`scholarship_schools\` ADD CONSTRAINT \`FK_4eff743284ccff252264c23cb72\` FOREIGN KEY (\`scholarship_id\`) REFERENCES \`scholarships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`scholarship_schools\` ADD CONSTRAINT \`FK_3fef790df49da84f639d06f2155\` FOREIGN KEY (\`school_id\`) REFERENCES \`schools\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`scholarship_schools\` DROP FOREIGN KEY \`FK_3fef790df49da84f639d06f2155\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_schools\` DROP FOREIGN KEY \`FK_4eff743284ccff252264c23cb72\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_programs\` DROP FOREIGN KEY \`FK_b9241075eedae37c941e50cc6bb\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_programs\` DROP FOREIGN KEY \`FK_ba2c20eccaff4301d1f58491640\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_fields_of_study\` DROP FOREIGN KEY \`FK_6fd5f51e72b59a7b1f732b2a370\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_fields_of_study\` DROP FOREIGN KEY \`FK_2a8f694223eaff9cba77ee59a70\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_degree_types\` DROP FOREIGN KEY \`FK_6a139df90c2b125c3f47ca14313\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_degree_types\` DROP FOREIGN KEY \`FK_1f424f8e81b88a5b8ab53932e3f\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_host_countries\` DROP FOREIGN KEY \`FK_8a77965357545fbb4b27809088b\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_host_countries\` DROP FOREIGN KEY \`FK_7eac5b06ff5f374ed6ff798b390\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_eligible_countries\` DROP FOREIGN KEY \`FK_980003b4cdcb862dc740e58ee9c\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_eligible_countries\` DROP FOREIGN KEY \`FK_eff92e5dc34bb9ffeb9b1e3b4c4\``);
        await queryRunner.query(`ALTER TABLE \`post_popularity_stats\` DROP FOREIGN KEY \`FK_9b73ccdda67c9b64ed499ff5616\``);
        await queryRunner.query(`ALTER TABLE \`post_views_events\` DROP FOREIGN KEY \`FK_698dc83e3d716c50f9091c3adff\``);
        await queryRunner.query(`ALTER TABLE \`post_views_events\` DROP FOREIGN KEY \`FK_85814f59790f207d9d419fe6819\``);
        await queryRunner.query(`ALTER TABLE \`comment_reports\` DROP FOREIGN KEY \`FK_52293400ae9e3142b0702cde49b\``);
        await queryRunner.query(`ALTER TABLE \`comment_reports\` DROP FOREIGN KEY \`FK_a7ed84b2cc95936b2b3b20051dc\``);
        await queryRunner.query(`ALTER TABLE \`comment_reports\` DROP FOREIGN KEY \`FK_45a6086948851a5e791f1b7964f\``);
        await queryRunner.query(`ALTER TABLE \`comment_reactions\` DROP FOREIGN KEY \`FK_b9fbc058a6dd52aec6c76f9b58a\``);
        await queryRunner.query(`ALTER TABLE \`comment_reactions\` DROP FOREIGN KEY \`FK_dc714054fc62b698018fcb0ae37\``);
        await queryRunner.query(`ALTER TABLE \`saved_posts\` DROP FOREIGN KEY \`FK_116e9df57f5221cc1a77c3d1cfe\``);
        await queryRunner.query(`ALTER TABLE \`saved_posts\` DROP FOREIGN KEY \`FK_2a6ac38aa1767f692d4f492639b\``);
        await queryRunner.query(`ALTER TABLE \`post_likes\` DROP FOREIGN KEY \`FK_9b9a7fc5eeff133cf71b8e06a7b\``);
        await queryRunner.query(`ALTER TABLE \`post_likes\` DROP FOREIGN KEY \`FK_b40d37469c501092203d285af80\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_23ad9291e0e22cdf46ae7ec5461\``);
        await queryRunner.query(`ALTER TABLE \`post_categories\` DROP FOREIGN KEY \`FK_f6e2655c798334198182db6399b\``);
        await queryRunner.query(`ALTER TABLE \`post_categories\` DROP FOREIGN KEY \`FK_becbe37977577e3eeb089b69fe1\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_312c63be865c81b922e39c2475e\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_d6f93329801a93536da4241e386\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_4c675567d2a58f0b07cef09c13d\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_259bf9825d9d198608d1b46b0b5\``);
        await queryRunner.query(`ALTER TABLE \`post_tags\` DROP FOREIGN KEY \`FK_192ab488d1c284ac9abe2e30356\``);
        await queryRunner.query(`ALTER TABLE \`post_tags\` DROP FOREIGN KEY \`FK_5df4e8dc2cb3e668b962362265d\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP FOREIGN KEY \`FK_94719521638e7220a028012ca42\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP FOREIGN KEY \`FK_d7a5344bdbf4566726fdc7c0a27\``);
        await queryRunner.query(`ALTER TABLE \`schools\` DROP FOREIGN KEY \`FK_251565bdb89c668899132acde38\``);
        await queryRunner.query(`ALTER TABLE \`saved_scholarships\` DROP FOREIGN KEY \`FK_51b0ad1d6f628a24d9931156759\``);
        await queryRunner.query(`ALTER TABLE \`saved_scholarships\` DROP FOREIGN KEY \`FK_321ce81c5ef86b9d2b3ed875e31\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_6ca9503d77ae39b4b5a6cc3ba88\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_applications\` DROP FOREIGN KEY \`FK_2c9e0c62af26956ca61f8616a7f\``);
        await queryRunner.query(`ALTER TABLE \`scholarship_applications\` DROP FOREIGN KEY \`FK_c278f9f1153a759bb4c0c149562\``);
        await queryRunner.query(`DROP INDEX \`IDX_3fef790df49da84f639d06f215\` ON \`scholarship_schools\``);
        await queryRunner.query(`DROP INDEX \`IDX_4eff743284ccff252264c23cb7\` ON \`scholarship_schools\``);
        await queryRunner.query(`DROP TABLE \`scholarship_schools\``);
        await queryRunner.query(`DROP INDEX \`IDX_b9241075eedae37c941e50cc6b\` ON \`scholarship_programs\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba2c20eccaff4301d1f5849164\` ON \`scholarship_programs\``);
        await queryRunner.query(`DROP TABLE \`scholarship_programs\``);
        await queryRunner.query(`DROP INDEX \`IDX_6fd5f51e72b59a7b1f732b2a37\` ON \`scholarship_fields_of_study\``);
        await queryRunner.query(`DROP INDEX \`IDX_2a8f694223eaff9cba77ee59a7\` ON \`scholarship_fields_of_study\``);
        await queryRunner.query(`DROP TABLE \`scholarship_fields_of_study\``);
        await queryRunner.query(`DROP INDEX \`IDX_6a139df90c2b125c3f47ca1431\` ON \`scholarship_degree_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f424f8e81b88a5b8ab53932e3\` ON \`scholarship_degree_types\``);
        await queryRunner.query(`DROP TABLE \`scholarship_degree_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_8a77965357545fbb4b27809088\` ON \`scholarship_host_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_7eac5b06ff5f374ed6ff798b39\` ON \`scholarship_host_countries\``);
        await queryRunner.query(`DROP TABLE \`scholarship_host_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_980003b4cdcb862dc740e58ee9\` ON \`scholarship_eligible_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_eff92e5dc34bb9ffeb9b1e3b4c\` ON \`scholarship_eligible_countries\``);
        await queryRunner.query(`DROP TABLE \`scholarship_eligible_countries\``);
        await queryRunner.query(`DROP TABLE \`post_popularity_stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_0c47f4aa3008e5d1c0d30048de\` ON \`post_views_events\``);
        await queryRunner.query(`DROP TABLE \`post_views_events\``);
        await queryRunner.query(`DROP TABLE \`comment_reports\``);
        await queryRunner.query(`DROP INDEX \`IDX_1b883ab118d832640b031ab685\` ON \`comment_reactions\``);
        await queryRunner.query(`DROP TABLE \`comment_reactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_f20a36cb4746cdc9d4012e636d\` ON \`saved_posts\``);
        await queryRunner.query(`DROP TABLE \`saved_posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_8f64693922a9e8c4e2605850d0\` ON \`post_likes\``);
        await queryRunner.query(`DROP TABLE \`post_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_420d9f679d41281f282f5bc7d0\` ON \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_8b0be371d28245da6e4f4b6187\` ON \`categories\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_f6e2655c798334198182db6399\` ON \`post_categories\``);
        await queryRunner.query(`DROP TABLE \`post_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_54ddf9075260407dcfdd724857\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_3cb61174373fe05492433f5811\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_312c63be865c81b922e39c2475\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_32e926dc2d4b4ec5beaa2e1bfc\` ON \`posts\``);
        await queryRunner.query(`DROP TABLE \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_2d41293984790c4b92ea0a1b73\` ON \`comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_d6f93329801a93536da4241e38\` ON \`comments\``);
        await queryRunner.query(`DROP TABLE \`comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_192ab488d1c284ac9abe2e3035\` ON \`post_tags\``);
        await queryRunner.query(`DROP TABLE \`post_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_d90243459a697eadb8ad56e909\` ON \`tags\``);
        await queryRunner.query(`DROP TABLE \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_b47cbb5311bad9c9ae17b8c1ed\` ON \`countries\``);
        await queryRunner.query(`DROP TABLE \`countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_7eb0b5c1fc27d6a1f1b98f18ca\` ON \`scholarships\``);
        await queryRunner.query(`DROP INDEX \`ft_scholarship_search\` ON \`scholarships\``);
        await queryRunner.query(`DROP INDEX \`idx_is_published\` ON \`scholarships\``);
        await queryRunner.query(`DROP INDEX \`idx_deadline\` ON \`scholarships\``);
        await queryRunner.query(`DROP INDEX \`idx_source\` ON \`scholarships\``);
        await queryRunner.query(`DROP INDEX \`idx_status\` ON \`scholarships\``);
        await queryRunner.query(`DROP INDEX \`idx_funding_type\` ON \`scholarships\``);
        await queryRunner.query(`DROP TABLE \`scholarships\``);
        await queryRunner.query(`DROP TABLE \`programs\``);
        await queryRunner.query(`DROP INDEX \`IDX_150b12170135ff067a24ea270d\` ON \`schools\``);
        await queryRunner.query(`DROP INDEX \`idx_schools_name\` ON \`schools\``);
        await queryRunner.query(`DROP INDEX \`idx_schools_country\` ON \`schools\``);
        await queryRunner.query(`DROP INDEX \`idx_schools_slug\` ON \`schools\``);
        await queryRunner.query(`DROP TABLE \`schools\``);
        await queryRunner.query(`DROP INDEX \`unique_save\` ON \`saved_scholarships\``);
        await queryRunner.query(`DROP TABLE \`saved_scholarships\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_users_email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_users_role_id\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_6ca9503d77ae39b4b5a6cc3ba8\` ON \`user_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_6ca9503d77ae39b4b5a6cc3ba8\` ON \`user_profiles\``);
        await queryRunner.query(`DROP INDEX \`idx_user_profiles_user_id\` ON \`user_profiles\``);
        await queryRunner.query(`DROP INDEX \`idx_user_profiles_is_complete\` ON \`user_profiles\``);
        await queryRunner.query(`DROP TABLE \`user_profiles\``);
        await queryRunner.query(`DROP TABLE \`scrape_jobs\``);
        await queryRunner.query(`DROP TABLE \`scholarship_applications\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`DROP INDEX \`idx_roles_name\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`fields_of_study\``);
        await queryRunner.query(`DROP TABLE \`degree_types\``);
    }

}
