export enum ApplicationStatus {
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  DOCUMENTS_UPLOADED = 'DOCUMENTS_UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RECOMMENDATION_ISSUED = 'RECOMMENDATION_ISSUED',
  SCHOOL_APPLIED = 'SCHOOL_APPLIED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}