export enum DocumentType {
  PASSPORT = 'PASSPORT',
  ACADEMIC_TRANSCRIPT = 'ACADEMIC_TRANSCRIPT',
  CV = 'CV',
  STATEMENT_OF_PURPOSE = 'STATEMENT_OF_PURPOSE',
  RECOMMENDATION_LETTER = 'RECOMMENDATION_LETTER',
  OTHERS = 'OTHERS',
}