export enum NotificationType {
  APPLICATION_STATUS = 'APPLICATION_STATUS',
  DOCUMENT_APPROVAL = 'DOCUMENT_APPROVAL',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  RECOMMENDATION_ADDED = 'RECOMMENDATION_ADDED',
  GENERAL = 'GENERAL',
}