export enum UserRole {
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  CONTENT_ADMIN = 'CONTENT_ADMIN',
  APPLICATION_MANAGER = 'APPLICATION_MANAGER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
}

